### ISSUE TITLE
shader compilation failed

### ISSUE THREAD

**Issue by Arihide** [xbpeng/DeepLoco#7]
I managed to build all the targets thanks to the previous issues.
Then, I tried to run the system with the command below.
`./DeepLoco -arg_file= args/test_args.txt `

However, I had the error

> Compiling shader: render/shaders/FullScreenQuad_VS.glsl
> shader compilation failed: render/shaders/FullScreenQuad_VS.glsl
> 0:1(1): error: syntax error, unexpected $end
> 
> Compiling shader: render/shaders/DownSample_PS.glsl
> shader compilation failed: render/shaders/DownSample_PS.glsl
> 0:1(1): error: syntax error, unexpected $end
> 
> shader linking failed
> Segmentation fault (core dumped)

`

**Comment by masa1120** [comment]
I could succeed to make everything. when I run ./DeepLoco -arg_file=~/DeepLoco-master/args/test_args.txt, "Buffer Assignment Failed: 00000501" is displayed on terminal. have you ever seen this statements? I will copy all statements of my screen. 

$ sudo ./DeepLoco -arg_file=~/args/test_args.txt
Compiling shader: render/shaders/FullScreenQuad_VS.glsl
Compiling shader: render/shaders/DownSample_PS.glsl
shader linking failed
Buffer Assignment Failed: 00000501
Buffer Assignment Failed: 00000501
Buffer Assignment Failed: 00000501
Buffer Assignment Failed: 00000501
Buffer Assignment Failed: 00000501
Buffer Assignment Failed: 00000501
Buffer Assignment Failed: 00000501
Buffer Assignment Failed: 00000501

**Comment by xbpeng** [comment]
Looks like an OpenGL issue. Not sure what is going on, but maybe it is similar to the issue here:
https://stackoverflow.com/questions/11138705/is-there-anything-wrong-with-my-glsl-shader-loading-code

**Comment by ghost** [comment]
Have you ever encountered this problem? is a cause also due to opengl? My OpenGL version is 4.5 and i use Quadro M4000 (NVIDIA) and OS is Ubuntu 16.04. I don't use OpenGL 3.3 needed oon intel HD Graphics. The small window whose title is TerrainRL was displayed but there is not displayed at all. The color of window is kept gray. When I pushed a key "q" on the small window, "Filmstrip mode enabled" is shown on the terminal. i think your logic itself is running in the back of the gray window. On my same machine, I tried your previous logic (Deep Terrain Learning). It was run and the good animation was displayed smoothly without any problem. I want to fix the window's condition being gray color. I need your help.

~$ DeepLoco -arg_file=args/test_args.txt
Compiling shader: render/shaders/FullScreenQuad_VS.glsl
Compiling shader: render/shaders/DownSample_PS.glsl
shader linking failed
Buffer Assignment Failed: 00000501
Buffer Assignment Failed: 00000501
Buffer Assignment Failed: 00000501
Buffer Assignment Failed: 00000501
Buffer Assignment Failed: 00000501
Buffer Assignment Failed: 00000501
Buffer Assignment Failed: 00000501
Buffer Assignment Failed: 00000501
Buffer Assignment Failed: 00000501

**Comment by abachaba** [comment]
Thank you for reply.
I've solved the problem.
It's just that I didn't move `DeepLoco` file from `/x64/Debug`

**Comment by Arihide** [comment]
Thank you for reply.
I've solved the problem.
It's just that I didn't move DeepLoco file from /x64/Debug
